// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ApkgCreator;
//
//    var ankiDeckInfo = AnkiDeckInfo.FromJson(jsonString);

namespace ApkgCreator
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class AnkiDeckInfo
    {
        [JsonProperty("@deckId")]
        public DeckId DeckId { get; set; }
    }

    public class DeckId
    {
        [JsonProperty("desc")]
        public string Desc { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("extendRev")]
        public long ExtendRev { get; set; }

        [JsonProperty("usn")]
        public long Usn { get; set; }

        [JsonProperty("collapsed")]
        public bool Collapsed { get; set; }

        [JsonProperty("newToday")]
        public List<long> NewToday { get; set; }

        [JsonProperty("timeToday")]
        public List<long> TimeToday { get; set; }

        [JsonProperty("dyn")]
        public long Dyn { get; set; }

        [JsonProperty("extendNew")]
        public long ExtendNew { get; set; }

        [JsonProperty("conf")]
        public long Conf { get; set; }

        [JsonProperty("revToday")]
        public List<long> RevToday { get; set; }

        [JsonProperty("lrnToday")]
        public List<long> LrnToday { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("mod")]
        public long Mod { get; set; }
    }
}
