// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ApkgCreator;
//
//    var ankiModel = AnkiModel.FromJson(jsonString);

namespace ApkgCreator.AdditionalModels
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class AnkiModel
    {
        public Model Model { get; set; }
    }

    public class Model
    {
        [JsonProperty("vers")]
        public List<object> Vers { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tags")]
        public List<object> Tags { get; set; }

        [JsonProperty("did")]
        public long Did { get; set; }

        [JsonProperty("usn")]
        public long Usn { get; set; }

        [JsonProperty("flds")]
        public List<Fld> Flds { get; set; }

        [JsonProperty("sortf")]
        public long Sortf { get; set; }

        [JsonProperty("tmpls")]
        public List<Tmpl> Tmpls { get; set; }

        [JsonProperty("mod")]
        public long Mod { get; set; }

        [JsonProperty("latexPost")]
        public string LatexPost { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("css")]
        public string Css { get; set; }

        [JsonProperty("latexPre")]
        public string LatexPre { get; set; }
    }

    public class Fld
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("media")]
        public List<object> Media { get; set; }

        [JsonProperty("sticky")]
        public bool Sticky { get; set; }

        [JsonProperty("rtl")]
        public bool Rtl { get; set; }

        [JsonProperty("ord")]
        public long Ord { get; set; }

        [JsonProperty("font")]
        public string Font { get; set; }

        [JsonProperty("size")]
        public long Size { get; set; }
    }

    public class Tmpl
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("qfmt")]
        public string Qfmt { get; set; }

        [JsonProperty("did")]
        public object Did { get; set; }

        [JsonProperty("bafmt")]
        public string Bafmt { get; set; }

        [JsonProperty("afmt")]
        public string Afmt { get; set; }

        [JsonProperty("ord")]
        public long Ord { get; set; }

        [JsonProperty("bqfmt")]
        public string Bqfmt { get; set; }
    }
}
