// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OxfordDictionaries;

namespace OxfordDictionaries.Migrations
{
    [DbContext(typeof(OxfordDictionariesCacheDbContext))]
    partial class OxfordDictionariesCacheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("OxfordDictionaries.DataModels.AudioFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("FileName");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("OxfordDictionaries.DataModels.LexicalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AudioFileId");

                    b.Property<string>("LexicalCategory");

                    b.Property<string>("OxfordDictionaryLexicalEntryV2Json");

                    b.Property<string>("Word");

                    b.HasKey("Id");

                    b.HasIndex("AudioFileId");

                    b.ToTable("LexicalEntries");
                });

            modelBuilder.Entity("OxfordDictionaries.DataModels.LexicalEntry", b =>
                {
                    b.HasOne("OxfordDictionaries.DataModels.AudioFile", "AudioFile")
                        .WithMany("LexicalEntries")
                        .HasForeignKey("AudioFileId");
                });
#pragma warning restore 612, 618
        }
    }
}
