// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OxfordDictionaries;
//
//    var oxfordDictionaryEntityV2 = OxfordDictionaryEntityV2.FromJson(jsonString);

namespace OxfordDictionaries
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OxfordDictionaryEntityV2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("metadata")]
        public OxfordDictionaryMetadataV2 Metadata { get; set; }

        [JsonProperty("results")]
        public List<OxfordDictionaryResultV2> Results { get; set; }

        [JsonProperty("word")]
        public string Word { get; set; }
    }

    public partial class OxfordDictionaryMetadataV2
    {
        [JsonProperty("operation")]
        public string Operation { get; set; }

        [JsonProperty("provider")]
        public string Provider { get; set; }

        [JsonProperty("schema")]
        public string Schema { get; set; }
    }

    public partial class OxfordDictionaryResultV2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("lexicalEntries")]
        public List<OxfordDictionaryLexicalEntryV2> LexicalEntries { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("word")]
        public string Word { get; set; }
    }

    public partial class OxfordDictionaryLexicalEntryV2
    {
        [JsonProperty("derivatives", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryLexicalCategoryV2> Derivatives { get; set; }

        [JsonProperty("entries")]
        public List<OxfordDictionaryEntryV2> Entries { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("lexicalCategory")]
        public OxfordDictionaryLexicalCategoryV2 LexicalCategory { get; set; }

        [JsonProperty("pronunciations")]
        public List<OxfordDictionaryPronunciationV2> Pronunciations { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class OxfordDictionaryLexicalCategoryV2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class OxfordDictionaryEntryV2
    {
        [JsonProperty("etymologies", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Etymologies { get; set; }

        [JsonProperty("homographNumber")]
        [JsonConverter(typeof(OxfordDictionaryParseStringConverterV2))]
        public long HomographNumber { get; set; }

        [JsonProperty("senses")]
        public List<OxfordDictionarySenseV2> Senses { get; set; }

        [JsonProperty("grammaticalFeatures", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryGrammaticalFeatureV2> GrammaticalFeatures { get; set; }
    }

    public partial class OxfordDictionaryGrammaticalFeatureV2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class OxfordDictionarySenseV2
    {
        [JsonProperty("definitions", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Definitions { get; set; }

        [JsonProperty("examples", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryExampleV2> Examples { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("shortDefinitions", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ShortDefinitions { get; set; }

        [JsonProperty("subsenses", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionarySubsenseV2> Subsenses { get; set; }

        [JsonProperty("thesaurusLinks", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryThesaurusLinkV2> ThesaurusLinks { get; set; }

        [JsonProperty("crossReferenceMarkers", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CrossReferenceMarkers { get; set; }

        [JsonProperty("crossReferences", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryGrammaticalFeatureV2> CrossReferences { get; set; }

        [JsonProperty("variantForms", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryVariantFormV2> VariantForms { get; set; }

        [JsonProperty("domains", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryLexicalCategoryV2> Domains { get; set; }
    }

    public partial class OxfordDictionaryExampleV2
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("notes", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryNoteV2> Notes { get; set; }
    }

    public partial class OxfordDictionaryNoteV2
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class OxfordDictionarySubsenseV2
    {
        [JsonProperty("definitions")]
        public List<string> Definitions { get; set; }

        [JsonProperty("examples", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryVariantFormV2> Examples { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("shortDefinitions")]
        public List<string> ShortDefinitions { get; set; }

        [JsonProperty("thesaurusLinks", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryThesaurusLinkV2> ThesaurusLinks { get; set; }

        [JsonProperty("domains", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryLexicalCategoryV2> Domains { get; set; }

        [JsonProperty("notes", NullValueHandling = NullValueHandling.Ignore)]
        public List<OxfordDictionaryNoteV2> Notes { get; set; }
    }

    public partial class OxfordDictionaryVariantFormV2
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class OxfordDictionaryThesaurusLinkV2
    {
        [JsonProperty("entry_id")]
        public string EntryId { get; set; }

        [JsonProperty("sense_id")]
        public string SenseId { get; set; }
    }

    public partial class OxfordDictionaryPronunciationV2
    {
        [JsonProperty("audioFile")]
        public Uri AudioFile { get; set; }

        [JsonProperty("dialects")]
        public List<string> Dialects { get; set; }

        [JsonProperty("phoneticNotation")]
        public string PhoneticNotation { get; set; }

        [JsonProperty("phoneticSpelling")]
        public string PhoneticSpelling { get; set; }
    }

    public partial class OxfordDictionaryEntityV2
    {
        public static OxfordDictionaryEntityV2 FromJson(string json) => JsonConvert.DeserializeObject<OxfordDictionaryEntityV2>(json, OxfordDictionaries.OxfordDictionaryConverterV2.Settings);
    }

    public static class OxfordDictionarySerializeV2
    {
        public static string ToJson(this OxfordDictionaryEntityV2 self) => JsonConvert.SerializeObject(self, OxfordDictionaries.OxfordDictionaryConverterV2.Settings);
    }

    internal static class OxfordDictionaryConverterV2
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class OxfordDictionaryParseStringConverterV2 : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly OxfordDictionaryParseStringConverterV2 Singleton = new OxfordDictionaryParseStringConverterV2();
    }
}
